# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


target 'Guidomia' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift', '~> 5.1.0', :inhibit_warnings => true
  pod 'RxCocoa', '~> 5.1.0'
  pod 'RxDataSources'
  pod 'RxGesture', '~> 3.0.2'

end
